-- MySQL Script generated by MySQL Workbench
-- Tue Jan 27 19:20:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `website` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `website` ;

-- -----------------------------------------------------
-- Table `website`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(90) NULL DEFAULT NULL,
  `bio` TEXT NULL DEFAULT NULL,
  `avatar_url` TEXT NULL DEFAULT NULL,
  `Repostsreposts_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`userposts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`userposts` (
  `post_id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `views` BIGINT NULL DEFAULT NULL,
  `likes` BIGINT NULL DEFAULT NULL,
  `reposts` BIGINT NULL DEFAULT NULL,
  `comments_count` BIGINT NULL DEFAULT NULL,
  `privacy_level` TINYINT(1) NULL DEFAULT NULL,
  `group_id` BIGINT NOT NULL,
  `Users_id` BIGINT NOT NULL,
  `PostMedia_id` BIGINT NOT NULL,
  `Likeslike_id` BIGINT NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_userposts_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_userposts_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `website`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`comments` (
  `comment_id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent_comment_id` BIGINT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `Usersuser_id` BIGINT NOT NULL,
  `UserPosts_id` BIGINT NOT NULL,
  `userposts_post_id` BIGINT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comments_userposts1_idx` (`userposts_post_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_userposts1`
    FOREIGN KEY (`userposts_post_id`)
    REFERENCES `website`.`userposts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`direct_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`direct_messages` (
  `message_id` BIGINT NOT NULL AUTO_INCREMENT,
  `sender_id` BIGINT NULL DEFAULT NULL,
  `receiver_id` BIGINT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `is_read` TINYINT(1) NULL DEFAULT NULL,
  `read_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`message_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`friendships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`friendships` (
  `friend_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `action_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`friend_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`usersgroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`usersgroups` (
  `group_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `ownerId` BIGINT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `avatar_url` TEXT NULL DEFAULT NULL,
  `is_public` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`groupmembers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`groupmembers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Groupsid` BIGINT NOT NULL,
  `groupId` BIGINT NULL DEFAULT NULL,
  `userId` BIGINT NULL DEFAULT NULL,
  `joined_at` TIMESTAMP NULL DEFAULT NULL,
  `role` ENUM('Admin', 'Moderator', 'User') NOT NULL DEFAULT 'User',
  `usersgroups_group_id` BIGINT NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groupmembers_usersgroups1_idx` (`usersgroups_group_id` ASC) VISIBLE,
  INDEX `fk_groupmembers_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_groupmembers_usersgroups1`
    FOREIGN KEY (`usersgroups_group_id`)
    REFERENCES `website`.`usersgroups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupmembers_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `website`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`groups_group_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`groups_group_members` (
  `Groupsid` BIGINT NOT NULL,
  `Group_membersid` BIGINT NOT NULL,
  PRIMARY KEY (`Groupsid`, `Group_membersid`),
  CONSTRAINT `FKGroups_Gro`
    FOREIGN KEY (`Groupsid`)
    REFERENCES `website`.`usersgroups` (`group_id`),
  CONSTRAINT `FKGroups_Gro694287`
    FOREIGN KEY (`Groupsid`)
    REFERENCES `website`.`usersgroups` (`group_id`),
  CONSTRAINT `FKGroups_Groups`
    FOREIGN KEY (`Groupsid`)
    REFERENCES `website`.`usersgroups` (`group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`likes` (
  `like_id` BIGINT NOT NULL AUTO_INCREMENT,
  `Users_id` BIGINT NOT NULL,
  `target_type` INT NULL DEFAULT NULL,
  `target_id` BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`like_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`postmedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`postmedia` (
  `media_id` BIGINT NOT NULL AUTO_INCREMENT,
  `UserPostsid` BIGINT NOT NULL,
  `post_id` BIGINT NULL DEFAULT NULL,
  `media_type` ENUM('Audio', 'Video', 'Image') NULL DEFAULT NULL,
  `url` TEXT NULL DEFAULT NULL,
  `mime_type` INT NULL DEFAULT NULL,
  `width` INT NULL DEFAULT NULL,
  `heigth` INT NULL DEFAULT NULL,
  `duration` TIME NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  `uploaded_at` TIMESTAMP NULL DEFAULT NULL,
  `likes_like_id` BIGINT NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  `usersgroups_group_id` BIGINT NOT NULL,
  PRIMARY KEY (`media_id`),
  INDEX `fk_postmedia_likes1_idx` (`likes_like_id` ASC) VISIBLE,
  INDEX `fk_postmedia_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_postmedia_usersgroups1_idx` (`usersgroups_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_postmedia_likes1`
    FOREIGN KEY (`likes_like_id`)
    REFERENCES `website`.`likes` (`like_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postmedia_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `website`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postmedia_usersgroups1`
    FOREIGN KEY (`usersgroups_group_id`)
    REFERENCES `website`.`usersgroups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`reposts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`reposts` (
  `reposts_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `original_post_id` BIGINT NULL DEFAULT NULL,
  `commentary` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`reposts_id`),
  INDEX `fk_reposts_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reposts_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `website`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`friendships_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`friendships_has_users` (
  `friendships_friend_id` BIGINT NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`friendships_friend_id`, `users_user_id`),
  INDEX `fk_friendships_has_users_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_friendships_has_users_friendships1_idx` (`friendships_friend_id` ASC) VISIBLE,
  CONSTRAINT `fk_friendships_has_users_friendships1`
    FOREIGN KEY (`friendships_friend_id`)
    REFERENCES `website`.`friendships` (`friend_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendships_has_users_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `website`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`users_has_direct_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`users_has_direct_messages` (
  `users_user_id` BIGINT NOT NULL,
  `direct_messages_message_id` BIGINT NOT NULL,
  PRIMARY KEY (`users_user_id`, `direct_messages_message_id`),
  INDEX `fk_users_has_direct_messages_direct_messages1_idx` (`direct_messages_message_id` ASC) VISIBLE,
  INDEX `fk_users_has_direct_messages_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_direct_messages_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `website`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_direct_messages_direct_messages1`
    FOREIGN KEY (`direct_messages_message_id`)
    REFERENCES `website`.`direct_messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`friendships_has_users1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`friendships_has_users1` (
  `friendships_friend_id` BIGINT NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`friendships_friend_id`, `users_user_id`),
  INDEX `fk_friendships_has_users1_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_friendships_has_users1_friendships1_idx` (`friendships_friend_id` ASC) VISIBLE,
  CONSTRAINT `fk_friendships_has_users1_friendships1`
    FOREIGN KEY (`friendships_friend_id`)
    REFERENCES `website`.`friendships` (`friend_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendships_has_users1_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `website`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `website`.`direct_messages_has_usersgroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `website`.`direct_messages_has_usersgroups` (
  `direct_messages_message_id` BIGINT NOT NULL,
  `usersgroups_group_id` BIGINT NOT NULL,
  PRIMARY KEY (`direct_messages_message_id`, `usersgroups_group_id`),
  INDEX `fk_direct_messages_has_usersgroups_usersgroups1_idx` (`usersgroups_group_id` ASC) VISIBLE,
  INDEX `fk_direct_messages_has_usersgroups_direct_messages1_idx` (`direct_messages_message_id` ASC) VISIBLE,
  CONSTRAINT `fk_direct_messages_has_usersgroups_direct_messages1`
    FOREIGN KEY (`direct_messages_message_id`)
    REFERENCES `website`.`direct_messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direct_messages_has_usersgroups_usersgroups1`
    FOREIGN KEY (`usersgroups_group_id`)
    REFERENCES `website`.`usersgroups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
